<section class="register">
	<h2>Register</h2>
<?php if ($this->error): ?>
	<p class="alert alert-warning">Please choose correct credentials for your registration.</p>
<?php endif ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array(
    'controller' => 'Register',
    'action' => 'index'
)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
    <dl class="zend_form">
    	<dt><?php echo $this->formLabel($form->get('email')); ?></dt>
        <dd>
            <?php
                echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'), array('class' => 'alert alert-danger'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd>
        	<?php
                echo $this->formElement($form->get('name'));
                echo $this->formElementErrors($form->get('name'), array('class' => 'alert alert-danger'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('password'));?></dt>
        <dd>
            <?php
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'), array('class' => 'alert alert-danger'));
            ?>
        </dd>
        <dd>
        	<?php
                echo $this->formElement($form->get('submit'));
                echo $this->formElementErrors($form->get('submit'), array('class' => 'alert alert-danger'));
            ?>
        </dd>
    </dl>
<?php echo $this->form()->closeTag() ?>
</section>
<!-- <form method="post" action="/users/Register/process"> -->
<!-- 	Name: <input type="text" name="name"> -->
<!-- 	<input type="submit" name="submit" value="Send"> -->
<!-- </form> -->
