<h1>Login</h1>
<?php if ($this->error) {
	echo '<p class="alert alert-danger">Invalid Credentials</p>';
}

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array(
    'controller' => 'Login',
    'action' => 'process'
)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

<dl class="zend_form">
    <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
    <dd>
        <?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'), array('class' => 'alert alert-danger'));
        ?>
    </dd>
    <dt><?php echo $this->formLabel($form->get('password'));?></dt>
    <dd>
        <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'), array('class' => 'alert alert-danger'));
        ?>
    </dd>
    <dd>
    	<?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'), array('class' => 'alert alert-danger'));
        ?>
    </dd>
</dl>
<?php echo $this->form()->closeTag() ?>
